ylimits = [-1,1];

yticks = -1:0.5:1;

figure
subplot(2,3,1), plot(RRF.signals.values(:)), grid on, title('RRF'), ylabel('Volts'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,2), plot(RVL.signals.values(:)), grid on, title('RVL'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,3), plot(RTA.signals.values(:)), grid on, title('RTA'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,4), plot(RGM.signals.values(:)), grid on, title('RGM'), ylabel('Volts'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,5), plot(RBF.signals.values(:)), grid on, title('RBF'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,6), plot(RLG.signals.values(:)), grid on, title('RLG'),...
    set(gca,'ytick',yticks), ylim(ylimits);
figure
subplot(2,3,1), plot(LRF.signals.values(:)), grid on, title('LRF'), ylabel('Volts'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,2), plot(LVL.signals.values(:)), grid on, title('LVL'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,3), plot(LTA.signals.values(:)), grid on, title('LTA'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,4), plot(LGM.signals.values(:)), grid on, title('LGM'), ylabel('Volts'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,5), plot(LBF.signals.values(:)), grid on, title('LBF'),...
    set(gca,'ytick',yticks), ylim(ylimits);
subplot(2,3,6), plot(LLG.signals.values(:)), grid on, title('LLG'),...
    set(gca,'ytick',yticks), ylim(ylimits);
% figure
% subplot(2,3,1), plot(L_fx.signals.values(:)), grid on, title('LFx'), ylabel('Newtons')
% subplot(2,3,2), plot(L_fy.signals.values(:)), grid on, title('LFy')
% subplot(2,3,3), plot(L_fz.signals.values(:)), grid on, title('LFz')
% subplot(2,3,4), plot(R_fx.signals.values(:)), grid on, title('RFx'), ylabel('Newtons')
% subplot(2,3,5), plot(R_fy.signals.values(:)), grid on, title('RFy')
% subplot(2,3,6), plot(R_fz.signals.values(:)), grid on, title('RFz')
% figure
% subplot(2,3,1), plot(angle.signals.values(:)), grid on, title('Crank Angle'), ylim([0 5]), ylabel('Volts'),...
%     set(gca,'ytick',0:0.5:5), ylim([0,5]);
% subplot(2,3,2), plot(LPed.signals.values(:)), grid on, title('L Pedal Angle')
% subplot(2,3,3), plot(RPed.signals.values(:)), grid on, title('R Pedal Angle')