% figure
% subplot(2,3,1), plot(RRF.signals.values(:)), grid on, title('RRF'), ylabel('Volts')
% subplot(2,3,2), plot(RVL.signals.values(:)), grid on, title('RVL')
% subplot(2,3,3), plot(RTA.signals.values(:)), grid on, title('RTA')
% subplot(2,3,4), plot(RGM.signals.values(:)), grid on, title('RGM'), ylabel('Volts')
% subplot(2,3,5), plot(RBF.signals.values(:)), grid on, title('RBF')
% subplot(2,3,6), plot(RLG.signals.values(:)), grid on, title('RLG')
% figure
% subplot(2,3,1), plot(LRF.signals.values(:)), grid on, title('LRF'), ylabel('Volts')
% subplot(2,3,2), plot(LVL.signals.values(:)), grid on, title('LVL')
% subplot(2,3,3), plot(LTA.signals.values(:)), grid on, title('LTA')
% subplot(2,3,4), plot(LGM.signals.values(:)), grid on, title('LGM'), ylabel('Volts')
% subplot(2,3,5), plot(LBF.signals.values(:)), grid on, title('LBF')
% subplot(2,3,6), plot(LLG.signals.values(:)), grid on, title('LLG')
figure
subplot(2,3,1), plot(L_fx_raw.signals.values(:)), grid on, title('LFx'), ylabel('Volts'),...
    set(gca,'ytick',-0.5:0.1:0.5), ylim([-0.5,0.5])
subplot(2,3,2), plot(L_fy_raw.signals.values(:)), grid on, title('LFy'),...
    set(gca,'ytick',-0.5:0.1:0.5), ylim([-0.5,0.5])
subplot(2,3,3), plot(L_fz_raw.signals.values(:)), grid on, title('LFz'),...
    set(gca,'ytick',-0.5:0.1:0.5), ylim([-0.5,0.5])
subplot(2,3,4), plot(R_fx_raw.signals.values(:)), grid on, title('RFx'), ylabel('Volts'),...
    set(gca,'ytick',-0.5:0.1:0.5), ylim([-0.5,0.5])
subplot(2,3,5), plot(R_fy_raw.signals.values(:)), grid on, title('RFy'),...
    set(gca,'ytick',-0.5:0.1:0.5), ylim([-0.5,0.5])
subplot(2,3,6), plot(R_fz_raw.signals.values(:)), grid on, title('RFz'),...
    set(gca,'ytick',-0.5:0.1:0.5), ylim([-0.5,0.5])

figure
subplot(2,2,1), plot(crank_angle.signals.values(:)), grid on, title('Crank Angle'), ylabel('Volts'),...
    set(gca,'ytick',0:0.5:5), ylim([0,5])
subplot(2,2,2), plot(L_pedal_angle.signals.values(:)), grid on, title('L Pedal Angle'), ylabel('Volts'),...
    set(gca,'ytick',0:0.5:10), ylim([0,10])
subplot(2,2,3), plot(raw_srm.signals.values(:)), grid on, title('PowerMeter(V)'), ylabel('Volts'),...
    set(gca,'ytick',-0.5:0.5:4), ylim([-0.5,4])
subplot(2,2,4), plot(R_pedal_angle.signals.values(:)), grid on, title('R Pedal Angle'), ylabel('Volts'),...
    set(gca,'ytick',0:0.5:10), ylim([0,10])

figure
subplot(2,3,1), plot(L_fx.signals.values(:)), grid on, title('LFx'), ylabel('Newtons'),...
    set(gca,'ytick',-150:20:150), ylim([-150,150])
subplot(2,3,2), plot(L_fy.signals.values(:)), grid on, title('LFy'),...
    set(gca,'ytick',-150:20:150), ylim([-150,150])
subplot(2,3,3), plot(L_fz.signals.values(:)), grid on, title('LFz'),...
    set(gca,'ytick',-150:20:150), ylim([-150,150])
subplot(2,3,4), plot(R_fx.signals.values(:)), grid on, title('RFx'), ylabel('Newtons'),...
    set(gca,'ytick',-150:20:150), ylim([-150,150])
subplot(2,3,5), plot(R_fy.signals.values(:)), grid on, title('RFy'),...
    set(gca,'ytick',-150:20:150), ylim([-150,150])
subplot(2,3,6), plot(R_fz.signals.values(:)), grid on, title('RFz'),...
    set(gca,'ytick',-150:20:150), ylim([-150,150])
